config/routes.rb
Campaignstop::Application.routes.draw do
  
  get "houses/create"

  get "houses/destroy"

  get "create/destroy"

  match "/campaigns/:id/join" => "users#join_campaign", :as => :join_campaign 
  match "/houses/create" => "houses#create", :as => :create_house
  match "campaigns/:id/manage" => "campaigns#manage", :as => :campaign_manage
  match "campaigns/:id/dispatch" => "campaigns#dispatch_houses", :as => :dispatch

  match "campaigns/:id/manage/houses" => "campaigns#manage_houses", :as => :manage_houses
  resources :campaigns
  devise_for :users
  
  get "users/:id", :to => "users#show", :as => :user

  root :to => "pages#home"
  
  get "pages/home"
  get "pages/about", :as => :about

  get "pages/contact", :as => :contact

end

app/models/campaign.rb
class Campaign
  include Mongoid::Document
  include Mongoid::Paperclip
  
  field :name, :type => String
  field :supporting, :type => String
  field :opposition, :type => String
  field :state, :type => String

  field :administrator_id, :type => String
  embeds_many :houses




  has_and_belongs_to_many :users

  has_mongoid_attached_file :image,
    :storage => :s3,
    :bucket => 'campaignstop',
    :styles => {:thumb => "75x75>", :small => "150x150>", :normal => "250x250>", :large => "450x450>" }, 
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension" 

  attr_accessible :name, :supporting, :opposition, :state, :administrator_id, :image


  #dispatch accepts a number of users and a number of hours and dispatches a number of houses
  #uses k-clustering
  
  def dispatch(num_users, num_hours)
    require 'open-uri'
    require 'json'
    
    puts "dispatch Called"
    a = 0.00001/2
    area_to_cover = area_to_cover(num_users, num_hours, a)

    
    @houses = self.houses
      
    house_mappings  = {}
    points = []
    @houses.each do |house|
       request = "http://maps.googleapis.com/maps/api/geocode/json?address=#{house.address},#{house.city},#{house.state}&sensor=false"
       request.gsub!(" ", "+")
       contents = open(request).read       
       google = JSON.parse(contents) 
       lat = google["results"][0]["geometry"]["location"]["lat"]
       long = google["results"][0]["geometry"]["location"]["lng"]
       point = [lat, long, house]
       points << point 
    end
  
    puts "Lat/long calculated" 
    clusters = get_clusters(points, area_to_cover)
 
    #output: points that the group should use (addresses)
    puts "Clusterslength: #{clusters.length}"
    first_cluster = nil
    clusters.each do |cluster|
      if cluster.length != 0
        first_cluster = cluster
      end

      
    end

    unformatted_solutions = []
    first_cluster.each do |point|
      unformatted_solutions << points[point]
    end

    solutions = unformatted_solutions.collect {|solution| solution[2] }

    return solutions
  end

  private 



  def area_to_cover(num_users, num_hours, a)
    return a*num_users*num_hours 

  end

  def get_clusters(points, area_covered)
    require 'rubygems'
    require 'k_means'
    
    puts "get clusters called"
    num_clusters = get_area(points)/area_covered

    data = points.collect {|point| [point[0],point[1]] }
    kmeans = KMeans.new(data, :centroids => num_clusters.to_i)
    
    puts "get clusters complete"
    return kmeans.view
    

  end


  def get_area(points)
     top_most_point = -100000000000000000
     left_most_point = 1000000000000000
     right_most_point = -1000000000000000
     bottom_most_point = 100000000000000


     pi = 3.1415926
     points.each do |point|
        if(point[0] > right_most_point)
          right_most_point = point[0]
        end

        if point[0] < left_most_point
          left_most_point = point[0]
        end

        if point[1] < bottom_most_point
          bottom_most_point = point[1]
        end

        if point[1] > top_most_point
          top_most_point = point[1]
        end
     end


     vertical = top_most_point - bottom_most_point
     horizontal = right_most_point - left_most_point

     average_diameter = (vertical+horizontal)/2
     
     radius = average_diameter/2

     return pi*(radius**2)
  end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    

  end
  
  def show
    @campaign = Campaign.find(params[:id])
    
  
  
  end

  def manage
    if user_signed_in? && current_user.campaign_administrator
      @campaign = Campaign.find(params[:id])

    else 
      redirect_to root_path
    end



  end


  def manage_houses
    if user_signed_in? && current_user.campaign_administrator
      @campaign = Campaign.find(params[:id])
      @houses = @campaign.houses


    else
      redirect_to root_path
    end

  end

  def dispatch_houses
    @campaign = Campaign.find(params[:id])
    num_users = 0

    params["user"].each do |user|
      if user.length !=0
         num_users = num_users = 1
      end
    end

    @houses = @campaign.dispatch(num_users, params[:time].to_i)

    @houses.each do |house|
      house.dispatched = true
      house.save!
  
    end

 end


  def new
    if current_user.campaign_administrator

    else
      redirect_to root_path
    end
  
  
  end

  def create
    if current_user.campaign_administrator
       @campaign = Campaign.create!(params[:campaign])
       redirect_to @campaign
    else
      redirect_to root_path
    end

  
  
  end

  def destroy
  end

  def edit
  end

  def update
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/create.html.erb
<h1>Campaigns#create</h1>
<p>Find me in app/views/campaigns/create.html.erb</p>

app/views/campaigns/destroy.html.erb
<h1>Campaigns#destroy</h1>
<p>Find me in app/views/campaigns/destroy.html.erb</p>

app/views/campaigns/dispatch_houses.html.erb
<%= render "shared/manage" %>

<h3>Dispatched Houses: </h3>

<div id="dispatch-page">
<ul>
  <% @houses.each do |house| %>
    <li><%= house.address %> <%= house.city %>,<%= house.state %></li>
  <% end %>
</ul>

</div>

app/views/campaigns/edit.html.erb
<h1>Campaigns#edit</h1>
<p>Find me in app/views/campaigns/edit.html.erb</p>

app/views/campaigns/manage.html.erb
<%= render "shared/manage" %>
     


<%= form_tag dispatch_path(@campaign) do %>
  <fieldset>
    <legend>Dispatch Volunteers </legend>
    <h3>Volunteers</h3>
    <% (0...10).each do |i| %>

      <div class="control-group">
        <div class="controls">
        
        <%= text_field_tag "user[#{i}]", "", :class => "user-input-field user-#{i} focused" %>
        </div>
      </div>
    
  <% end %>
  
  <%= link_to "More", "#", :id => "more-user" %>
  <div class="control-group">
    <h3>Allotted Time (in hours)</h3>
    <div class="controls">
    <%= text_field_tag "time","", :class => "focused" %>
  </div>

  </div>
  <%= submit_tag "Dispatch", :class => "btn-primary" %>
</fieldset>
<% end %>


<h3>Volunteers: </h3>

<ul>
  <% @campaign.users.each do |user| %>
    <li><%= user.name %></li>

  <% end %>

</ul>

<script type="text/javascript">
  $(".user-input-field").hide();
  $(".user-0").show();

  
  var i = 1;
  $("#more-user").click(function(){
       $(".user-" + i).fadeIn();
       i++;
      
  });



</script>

app/views/campaigns/manage_houses.html.erb
<%= render "shared/manage" %>



<%= form_for(House.new,:url => create_house_path) do |f| %>

  <fieldset>
  <legend>Add House</legend>
     <div class="control-group">

      <%= f.label :address, :class => "control-label" %>
      <div class="controls">

        <%= f.text_field :address, :class => "input-xlarge focused", :id => "focusedInput" %>
      </div>

    </div> 

    <div class="control-group">

      <%= f.label :city, :class => "control-label" %>
      <div class="controls">

        <%= f.text_field :city, :class => "input-xlarge focused", :id => "focusedInput" %>
      </div>

    </div>

    <div class="control-group">

      <%= f.label :state, :class => "control-label" %>
      <div class="controls">

        <%= f.text_field :state, :class => "input-xlarge focused", :id => "focusedInput" %>
      </div>

    </div>

    <div class="control-group">

      <%= f.label :zip, :class => "control-label" %>
      <div class="controls">

        <%= f.text_field :zip, :class => "input-xlarge focused", :id => "focusedInput" %>
      </div>

    </div>

  <%= f.hidden_field :campaign_id, :value => @campaign.id.to_s %>
  <%= f.submit "Add House" %>
  </fieldset>
<% end %> 
  
 <ul>
  <% @campaign.houses.each do |house| %>
    <li><%= house.address %> <%= house.city %>, <%= house.state %> <%= house.zip %></li>

  <% end %>



</ul>

app/views/campaigns/new.html.erb
<%= form_for Campaign.new, :html => {:multipart => true } do |f|%>
  <fieldset>
    <legend>New Campaign</legend>
    <div class="control-group">
      <%= f.label :name %>
      <div class="controls">
        
        <%= f.text_field :name %>

      </div>
    </div>

    <div class="control-group">
      <%= f.label "For: " %>
      <div class="controls">
        
        <%= f.text_field :supporting %>

      </div>
    </div>
   
    <div class="control-group">
      <%= f.label "Logo" %>
      <div class="controls">
        
        <%= f.file_field :image %>

      </div>
    </div>
   <div class="control-group">
      <div class="controls">
        <%= f.hidden_field :administrator_id, :value => current_user.id.to_s %>
        <%= f.submit "Create Campaign", :class => "btn btn-primary"  %>
      </div>
    </div>

  </fieldset>



<% end %>

app/views/campaigns/show.html.erb
<ul class=thumbnails>
  <li class="span4">
    <div class="thumbnail">
    <%= image_tag @campaign.image.url(:large) %>
    <div class="caption">
      <h1><%= @campaign.name %></h1>

    </div>
  </div>
  </li>
</ul>

<% if !@campaign.users.include?(current_user) %><%= link_to "Join Campaign", join_campaign_path(@campaign), :class => "btn btn-primary" %><% end %> 

<% if @campaign.administrator_id && @campaign.administrator_id.to_s == current_user.id.to_s %> <%= link_to "Manage Your Campaign", campaign_manage_path, :class => "btn btn-danger" %> <% end %>

<h3>Volunteers: </h3>


<ul>
  <% @campaign.users.each do |user| %>
    <li>
      <%= user.name %>

    </li>

  <% end %>

</ul>

app/views/campaigns/update.html.erb
<h1>Campaigns#update</h1>
<p>Find me in app/views/campaigns/update.html.erb</p>